'use strict';

async function bitmapToTensor(bitmap){const c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d',{willReadFrequently:true,alpha:false});ctx.fillStyle='#000';ctx.fillRect(0,0,W,H);const bw=bitmap.width||bitmap.naturalWidth,bh=bitmap.height||bitmap.naturalHeight,scale=Math.max(W/bw,H/bh),dw=bw*scale,dh=bh*scale;ctx.drawImage(bitmap,(W-dw)/2,(H-dh)/2,dw,dh);return tf.tidy(()=>tf.browser.fromPixels(c).toFloat().div(255).expandDims(0))}
async function loadImageTensor(item){if(item.blob&&typeof createImageBitmap==='function'){const bmp=await createImageBitmap(item.blob);try{return await bitmapToTensor(bmp)}finally{bmp.close?.()}}return new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=async()=>{try{resolve(await bitmapToTensor(img))}catch(e){reject(e)}};img.onerror=()=>reject(Error('Image could not be loaded. The host may block cross-origin pixel access.'));img.src=itemUrl(item)})}

async function trainOne(item){let target=null;try{compileModel(model);target=await loadImageTensor(item);const steps=clamp(Math.floor(Number($('#steps').value)||40),1,500),replayN=clamp(Math.floor(Number($('#replayN').value)||0),0,3);let latest=0;for(let s=0;s<steps&&!stopRequested;s++){const prompt=item.caption||item.title||'image',inputs=[Array.from(inputVector(prompt)),Array.from(inputVector(prompt))],yParts=[target,target],temp=[];for(let k=0;k<replayN&&replay.length;k++){const e=replay[(Math.random()*replay.length)|0];inputs.push(Array.from(inputVector(e.prompt)));const rt=tf.tensor4d(e.pixels,[1,H,W,3]);temp.push(rt);yParts.push(rt)}const xs=tf.tensor2d(inputs,[inputs.length,INPUT]),ys=tf.concat(yParts,0),loss=await model.trainOnBatch(xs,ys);latest=Array.isArray(loss)?loss[0]:loss;xs.dispose();ys.dispose();temp.forEach(t=>t.dispose());$('#progress').style.width=((s+1)/steps*100).toFixed(1)+'%';if((s&3)===0){$('#loss').textContent=Number(latest).toFixed(5);await tf.nextFrame()}}if(stopRequested)return false;const pixels=Float32Array.from(await target.data());replay.push({prompt:item.caption||item.title||'image',pixels});if(replay.length>REPLAY_MAX)replay.shift();trainedCount++;losses.push(Number(latest));if(losses.length>120)losses.shift();history.unshift({title:item.title||'Image',prompt:item.caption||'',source:item.source||'',kind:item.kind||'image',loss:Number(latest),time:Date.now()});history=history.slice(0,160);updateStats();saveMeta();await saveReplayDB();drawLoss();log(`Trained image #${trainedCount}: ${item.title} · loss ${Number(latest).toFixed(5)}`);if($('#autosave').checked)await saveBrowser(false);await generate();return true}finally{target?.dispose()}}
async function trainSelected(advance=false,forceSequence=false){if(busy||!selected||!model)return;busy=true;stopRequested=false;$('#stop').disabled=false;$('#trainState').textContent='training';updateBusyUI();let continueAll=forceSequence||$('#autoSequence').checked;try{do{const item=selected;if(!item)break;const committed=await trainOne(item);if(!committed||stopRequested)break;if(advance||continueAll){const hasNext=nextResult();if(!hasNext)break}else break;if(!continueAll)break;await tf.nextFrame()}while(!stopRequested)}catch(e){log('Training failed: '+e.message);console.error(e)}finally{busy=false;$('#stop').disabled=true;$('#trainState').textContent=stopRequested?'stopped':'idle';$('#progress').style.width='0%';updateBusyUI();showSelected()}}
function updateBusyUI(){const lock=busy;$('#trainOnly').disabled=lock||!selected;$('#trainNext').disabled=lock||!selected;$('#trainQueue').disabled=lock||!results.length;$('#clearQueue').disabled=lock||!results.length;$('#newModel').disabled=lock;$('#loadBrowser').disabled=lock}

function updateStats(){$('#trained').textContent=trainedCount;$('#replayCount').textContent=replay.length;$('#loss').textContent=losses.length?Number(losses.at(-1)).toFixed(5):'—';$('#queueMetric').textContent=results.length;renderHistory()}
function drawLoss(){const c=$('#lossCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#080c12';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#26344b';ctx.beginPath();for(let i=1;i<4;i++){const y=h*i/4;ctx.moveTo(0,y);ctx.lineTo(w,y)}ctx.stroke();if(losses.length<2)return;let max=Math.max(...losses),min=Math.min(...losses);if(max===min)max=min+1e-6;ctx.strokeStyle='#7ee7bf';ctx.lineWidth=2;ctx.beginPath();losses.forEach((v,i)=>{const x=i/(losses.length-1)*(w-8)+4,y=h-4-(v-min)/(max-min)*(h-8);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
async function generate(){if(!model)return;const prompt=$('#genPrompt').value.trim()||'untitled',seed=$('#seed').value||'1',x=tf.tensor2d([Array.from(inputVector(prompt,hash32(seed)))],[1,INPUT]);let y;try{y=model.predict(x);await tf.browser.toPixels(y.squeeze(),$('#gen'))}finally{x.dispose();y?.dispose()}}
async function saveBrowser(noisy=true){if(!model)return;try{await model.save('indexeddb://'+MODEL_KEY);saveMeta();await saveReplayDB();setState('saved',true);if(noisy)log('Model + replay checkpoint saved to IndexedDB.')}catch(e){log('Save failed: '+e.message)}}
async function loadBrowser(){if(busy)return;try{const known=await tf.io.listModels(),key=known['indexeddb://'+MODEL_KEY]?MODEL_KEY:LEGACY_MODEL_KEY,m=await tf.loadLayersModel('indexeddb://'+key);model?.dispose();model=m;compileModel(model);restoreMeta();if(key===MODEL_KEY)await loadReplayDB();else replay=[];updateStats();setState('browser save loaded',true);log('Loaded browser checkpoint.');await generate()}catch(e){log('No browser checkpoint could be loaded: '+e.message)}}
async function loadModelFiles(files){const list=[...files],json=list.find(f=>f.name.endsWith('.json')),bins=list.filter(f=>f.name.endsWith('.bin'));if(!json||!bins.length){log('Choose the exported model.json and at least one .bin weights file together.');return}try{const m=await tf.loadLayersModel(tf.io.browserFiles([json,...bins]));model?.dispose();model=m;compileModel(model);replay=[];updateStats();setState('files loaded',true);log('Loaded model files. Replay memory starts empty for exported weights.');await generate()}catch(e){log('Model file load failed: '+e.message)}}
function renderHistory(){const el=$('#history');if(!history.length){el.innerHTML='<div class="hint">No training history yet.</div>';return}el.innerHTML=history.map(h=>`<div class="historyitem"><span>${escapeHtml(h.title)}</span><b>${Number(h.loss||0).toFixed(4)}</b></div>`).join('')}
